# Generated by Django 5.2.17 on 2026-09-09 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='numéro')),
                ('type', models.CharField(choices=[('INDIVIDUELLE', 'Individuelle'), ('DOUBLE', 'Double'), ('COMMUNE', 'Commune')], default='COMMUNE', max_length=12, verbose_name='type')),
            ],
            options={
                'verbose_name': 'chambre',
                'verbose_name_plural': 'chambres',
                'ordering': ['service__nom', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='numéro / libellé')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NETTOYAGE', 'En nettoyage'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', help_text='Hors occupation : un lit occupé est déduit des séjours en cours.', max_length=12, verbose_name='statut')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hospitalisation.chambre', verbose_name='chambre')),
            ],
            options={
                'verbose_name': 'lit',
                'verbose_name_plural': 'lits',
                'ordering': ['chambre__service__nom', 'chambre__numero', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('motif', models.CharField(max_length=255, verbose_name="motif d'hospitalisation")),
                ('diagnostic_admission', models.TextField(blank=True, verbose_name="diagnostic à l'admission")),
                ('date_admission', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'admission")),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SORTIE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=10, verbose_name='statut')),
                ('date_sortie', models.DateTimeField(blank=True, null=True, verbose_name='date de sortie')),
                ('mode_sortie', models.CharField(blank=True, choices=[('DOMICILE', 'Retour à domicile'), ('TRANSFERT', 'Transfert vers un autre établissement'), ('CONTRE_AVIS', 'Sortie contre avis médical'), ('DECES', 'Décès')], max_length=12, verbose_name='mode de sortie')),
                ('compte_rendu', models.TextField(blank=True, verbose_name="compte-rendu d'hospitalisation")),
                ('consignes_sortie', models.TextField(blank=True, verbose_name='consignes de sortie')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations', to='consultations.consultation', verbose_name="consultation d'origine")),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('medecin_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_referees', to=settings.AUTH_USER_MODEL, verbose_name='médecin référent')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='patients.patient', verbose_name='patient')),
                ('lit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations', to='hospitalisation.lit', verbose_name='lit')),
            ],
            options={
                'verbose_name': 'hospitalisation',
                'verbose_name_plural': 'hospitalisations',
                'ordering': ['-date_admission'],
            },
        ),
        migrations.CreateModel(
            name='MouvementLit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_lit', to='hospitalisation.hospitalisation')),
                ('lit_nouveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hospitalisation.lit')),
                ('lit_precedent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hospitalisation.lit')),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mouvement de lit',
                'verbose_name_plural': 'mouvements de lit',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NoteSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SOIN', 'Soin infirmier'), ('OBSERVATION', 'Observation médicale'), ('TRAITEMENT', 'Administration de traitement'), ('CONSTANTES', 'Relevé de constantes'), ('AUTRE', 'Autre')], default='SOIN', max_length=12, verbose_name='type')),
                ('description', models.TextField(verbose_name='description')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='température (°C)')),
                ('tension_systolique', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TA systolique')),
                ('tension_diastolique', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TA diastolique')),
                ('pouls', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='pouls (bpm)')),
                ('date_note', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hospitalisation.hospitalisation', verbose_name='séjour')),
            ],
            options={
                'verbose_name': 'note de suivi',
                'verbose_name_plural': 'notes de suivi',
                'ordering': ['-date_note'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('code', models.CharField(blank=True, max_length=12, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to=settings.AUTH_USER_MODEL, verbose_name='médecin responsable')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='hospitalisation.service', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='hospitalisation.service', verbose_name='service'),
        ),
        migrations.AddConstraint(
            model_name='lit',
            constraint=models.UniqueConstraint(fields=('chambre', 'numero'), name='lit_unique_par_chambre'),
        ),
        migrations.AddIndex(
            model_name='hospitalisation',
            index=models.Index(fields=['statut', '-date_admission'], name='hospitalisa_statut_6c848c_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalisation',
            index=models.Index(fields=['patient', '-date_admission'], name='hospitalisa_patient_552f13_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitalisation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'EN_COURS')), fields=('lit',), name='un_seul_sejour_en_cours_par_lit'),
        ),
        migrations.AddConstraint(
            model_name='chambre',
            constraint=models.UniqueConstraint(fields=('service', 'numero'), name='chambre_unique_par_service'),
        ),
    ]
