# Generated by Django 5.2.17 on 2026-09-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rattacher_donnees_existantes'),
        ('core', '0005_etablissement_obligatoire'),
        ('hospitalisation', '0002_chambre_etablissement_hospitalisation_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='lit',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='mouvementlit',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='notesuivi',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='service',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
    ]
