# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_etablissement_historiqueaction_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('tous', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='etablissement',
            field=models.ForeignKey(blank=True, help_text='Vide pour un super-administrateur de la plateforme.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='matricule'),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(fields=('etablissement', 'matricule'), name='utilisateur_matricule_par_etablissement'),
        ),
    ]
