# Generated by Django 5.2.17 on 2026-09-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_utilisateur_managers_utilisateur_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrateur'), ('MEDECIN', 'Médecin'), ('INFIRMIER', 'Infirmier(ère)'), ('PHARMACIEN', 'Pharmacien(ne)'), ('LABORANTIN', 'Laborantin(e)'), ('RADIOLOGUE', "Radiologue / agent d'imagerie"), ('AGENT_ACCUEIL', "Agent d'accueil"), ('COMPTABLE', 'Comptable'), ('SAGE_FEMME', 'Sage-femme'), ('CHIRURGIEN', 'Chirurgien(ne)'), ('ANESTHESISTE', 'Médecin anesthésiste-réanimateur'), ('IBODE', 'Infirmier(ère) de bloc opératoire (IBODE)'), ('AGENT_STERILISATION', 'Agent de stérilisation'), ('CADRE_BLOC', 'Agent de programmation / cadre de bloc')], help_text='Détermine les fonctions et les données accessibles (RBAC).', max_length=32, verbose_name='rôle'),
        ),
    ]
