# Generated by Django 5.2.17 on 2026-09-09 10:37

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('COMPLETE', 'Complète'), ('PARTIELLE', 'Partielle'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=12, verbose_name='statut')),
                ('date_delivrance', models.DateTimeField(blank=True, null=True, verbose_name='date de délivrance')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='commentaire')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispensation', to='consultations.ordonnance', verbose_name='ordonnance')),
                ('pharmacien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations', to=settings.AUTH_USER_MODEL, verbose_name='pharmacien')),
            ],
            options={
                'verbose_name': 'dispensation',
                'verbose_name_plural': 'dispensations',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(blank=True, help_text='Code interne ou code-barres, facultatif.', max_length=30, null=True, unique=True, verbose_name='code')),
                ('denomination', models.CharField(max_length=200, verbose_name='dénomination (DCI)')),
                ('dosage', models.CharField(blank=True, help_text='Ex. : 500 mg, 1 g/10 ml…', max_length=60, verbose_name='dosage')),
                ('forme', models.CharField(choices=[('COMPRIME', 'Comprimé'), ('GELULE', 'Gélule'), ('SIROP', 'Sirop'), ('SUSPENSION', 'Suspension buvable'), ('INJECTABLE', 'Injectable'), ('PERFUSION', 'Solution pour perfusion'), ('POMMADE', 'Pommade / crème'), ('COLLYRE', 'Collyre'), ('SUPPOSITOIRE', 'Suppositoire'), ('AUTRE', 'Autre')], default='COMPRIME', max_length=20, verbose_name='forme galénique')),
                ('unite', models.CharField(default='unité', help_text='Ex. : comprimé, flacon, ampoule, tube…', max_length=30, verbose_name='unité de délivrance')),
                ('seuil_alerte', models.PositiveIntegerField(default=10, help_text='En dessous de ce stock utilisable, le médicament est signalé.', verbose_name="seuil d'alerte")),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'médicament',
                'verbose_name_plural': 'médicaments',
                'ordering': ['denomination', 'dosage'],
            },
        ),
        migrations.CreateModel(
            name='LotMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=60, verbose_name='numéro de lot')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité restante')),
                ('quantite_initiale', models.PositiveIntegerField(verbose_name='quantité initiale')),
                ('date_peremption', models.DateField(verbose_name='date de péremption')),
                ('date_reception', models.DateField(default=datetime.date.today, verbose_name='date de réception')),
                ('fournisseur', models.CharField(blank=True, max_length=150, verbose_name='fournisseur')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacie.medicament', verbose_name='médicament')),
            ],
            options={
                'verbose_name': 'lot de médicament',
                'verbose_name_plural': 'lots de médicaments',
                'ordering': ['date_peremption', 'date_reception'],
            },
        ),
        migrations.CreateModel(
            name='LigneDispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_dispensee', models.PositiveIntegerField(verbose_name='quantité délivrée')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('dispensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.dispensation')),
                ('ligne_ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_dispensation', to='consultations.ligneordonnance')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pharmacie.lotmedicament')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacie.medicament')),
            ],
            options={
                'verbose_name': 'ligne de dispensation',
                'verbose_name_plural': 'lignes de dispensation',
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='InteractionMedicamenteuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravite', models.CharField(choices=[('MINEURE', 'Mineure'), ('MODEREE', 'Modérée'), ('MAJEURE', 'Majeure'), ('CONTRE_INDIQUEE', 'Association contre-indiquée')], default='MODEREE', max_length=16, verbose_name='gravité')),
                ('description', models.TextField(blank=True, verbose_name='description / conduite à tenir')),
                ('medicament_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_a', to='pharmacie.medicament')),
                ('medicament_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_b', to='pharmacie.medicament')),
            ],
            options={
                'verbose_name': 'interaction médicamenteuse',
                'verbose_name_plural': 'interactions médicamenteuses',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée (réception)'), ('SORTIE', 'Sortie (dispensation)'), ('AJUST_POS', 'Ajustement positif (inventaire)'), ('AJUST_NEG', 'Ajustement négatif (inventaire, casse)'), ('PEREMPTION', 'Retrait pour péremption')], max_length=12, verbose_name='type')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('reference', models.CharField(blank=True, help_text='Ex. : n° de dispensation.', max_length=60, verbose_name='référence')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='pharmacie.lotmedicament', verbose_name='lot')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacie.medicament', verbose_name='médicament')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='opérateur')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='medicament',
            index=models.Index(fields=['denomination'], name='pharmacie_m_denomin_bfc581_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotmedicament',
            constraint=models.UniqueConstraint(fields=('medicament', 'numero_lot'), name='lot_unique_par_medicament'),
        ),
        migrations.AddConstraint(
            model_name='interactionmedicamenteuse',
            constraint=models.UniqueConstraint(fields=('medicament_a', 'medicament_b'), name='interaction_paire_unique'),
        ),
    ]
