# Generated by Django 5.2.17 on 2026-09-10 16:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Utilisé pour la facturation des dispensations (CDC 4.8).', max_digits=10, verbose_name='prix unitaire de vente (FCFA)'),
        ),
    ]
