# Generated by Django 5.2.17 on 2026-09-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rattacher_donnees_existantes'),
        ('core', '0005_etablissement_obligatoire'),
        ('pharmacie', '0003_dispensation_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensation',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='interactionmedicamenteuse',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='lignedispensation',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='lotmedicament',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
    ]
