# Generated by Django 5.2.17 on 2026-09-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_etablissement_obligatoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='prescriptible_sage_femme',
            field=models.BooleanField(default=False, help_text="Cochez pour les médicaments qu'une sage-femme peut prescrire (fer, acide folique, SP, paracétamol…).", verbose_name='prescriptible par une sage-femme'),
        ),
    ]
