# Generated by Django 5.2.17 on 2026-09-10 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_initial'),
        ('hospitalisation', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('categorie', models.CharField(choices=[('BIOLOGIE', 'Analyse biologique'), ('IMAGERIE', 'Imagerie médicale')], max_length=10, verbose_name='catégorie')),
                ('unite', models.CharField(blank=True, help_text='Ex. : g/L, /mm³ (biologie).', max_length=30, verbose_name='unité')),
                ('valeurs_reference', models.CharField(blank=True, help_text='Ex. : 3.5 - 5.0', max_length=120, verbose_name='valeurs de référence')),
                ('delai_rendu_heures', models.PositiveSmallIntegerField(default=24, verbose_name='délai de rendu (heures)')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': "type d'examen",
                'verbose_name_plural': "types d'examen",
                'ordering': ['categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='DemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('categorie', models.CharField(choices=[('BIOLOGIE', 'Analyse biologique'), ('IMAGERIE', 'Imagerie médicale')], max_length=10, verbose_name='catégorie')),
                ('priorite', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', max_length=8, verbose_name='priorité')),
                ('renseignements_cliniques', models.TextField(blank=True, verbose_name='renseignements cliniques')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de la demande')),
                ('date_prelevement', models.DateTimeField(blank=True, null=True, verbose_name='date de prélèvement')),
                ('statut', models.CharField(choices=[('DEMANDEE', 'Demandée'), ('EN_COURS', 'En cours'), ('RESULTATS', 'Résultats disponibles'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='DEMANDEE', max_length=10, verbose_name='statut')),
                ('motif_annulation', models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation")),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examen', to='consultations.consultation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examen', to='hospitalisation.hospitalisation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_examen', to='patients.patient', verbose_name='patient')),
                ('prescripteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examen_prescrites', to=settings.AUTH_USER_MODEL, verbose_name='prescripteur')),
            ],
            options={
                'verbose_name': "demande d'examen",
                'verbose_name_plural': "demandes d'examen",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='LigneExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='unité')),
                ('valeurs_reference', models.CharField(blank=True, max_length=120, verbose_name='valeurs de référence')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='laboratoire.demandeexamen', verbose_name='demande')),
                ('type_examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='laboratoire.typeexamen', verbose_name='examen')),
            ],
            options={
                'verbose_name': "ligne d'examen",
                'verbose_name_plural': "lignes d'examen",
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(blank=True, max_length=120, verbose_name='valeur mesurée')),
                ('interpretation', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('BAS', 'Anormal — bas'), ('HAUT', 'Anormal — haut'), ('ANORMAL', 'Anormal'), ('NON_INTERPRETABLE', 'Non interprétable')], max_length=20, verbose_name='interprétation')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='compte-rendu')),
                ('conclusion', models.TextField(blank=True, verbose_name='conclusion')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='laboratoire/resultats/%Y/%m/', verbose_name='pièce jointe (image / PDF)')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='commentaire')),
                ('saisi_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='saisi le')),
                ('valide', models.BooleanField(default=False, verbose_name='validé')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('ligne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='laboratoire.ligneexamen', verbose_name='ligne')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'résultat',
                'verbose_name_plural': 'résultats',
            },
        ),
        migrations.AddIndex(
            model_name='demandeexamen',
            index=models.Index(fields=['categorie', 'statut', '-date_demande'], name='laboratoire_categor_ef5e59_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeexamen',
            index=models.Index(fields=['patient', '-date_demande'], name='laboratoire_patient_a83d29_idx'),
        ),
        migrations.AddConstraint(
            model_name='ligneexamen',
            constraint=models.UniqueConstraint(fields=('demande', 'type_examen'), name='ligne_examen_unique'),
        ),
    ]
