# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_constantes_etablissement_consultation_etablissement_and_more'),
        ('core', '0003_etablissement_historiqueaction_etablissement_and_more'),
        ('hospitalisation', '0002_chambre_etablissement_hospitalisation_etablissement_and_more'),
        ('laboratoire', '0001_initial'),
        ('patients', '0002_allergie_etablissement_dossiermedical_etablissement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamen',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='ligneexamen',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='typeexamen',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='demandeexamen',
            name='reference',
            field=models.CharField(editable=False, max_length=20, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='typeexamen',
            name='code',
            field=models.CharField(max_length=30, verbose_name='code'),
        ),
        migrations.AddConstraint(
            model_name='demandeexamen',
            constraint=models.UniqueConstraint(fields=('etablissement', 'reference'), name='demandeexamen_reference_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='typeexamen',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='typeexamen_code_par_etablissement'),
        ),
    ]
