# Generated by Django 5.2.17 on 2026-09-10 16:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assurances', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('categorie', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('HOSPIT_JOUR', 'Hospitalisation (par jour)'), ('ACTE_BLOC', 'Acte de bloc opératoire'), ('MEDICAMENT', 'Médicament'), ('ANALYSE', 'Analyse / imagerie'), ('AUTRE', 'Autre')], max_length=16, verbose_name='catégorie')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant (FCFA)')),
                ('reference_externe', models.CharField(blank=True, help_text="Ex. : identifiant d'un type d'intervention pour un tarif d'acte.", max_length=40, verbose_name='référence externe')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'tarif',
                'verbose_name_plural': 'grille tarifaire',
                'ordering': ['categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('date_emission', models.DateField(default=datetime.date.today, verbose_name="date d'émission")),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PARTIELLE', 'Partiellement réglée'), ('REGLEE', 'Réglée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=10, verbose_name='statut')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='montant total')),
                ('taux_couverture_applique', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux de couverture appliqué (%)')),
                ('part_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='part assurance')),
                ('part_patient', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='part patient')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('motif_annulation', models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation")),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='patients.patient', verbose_name='patient')),
                ('patient_assure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='assurances.patientassure', verbose_name='couverture appliquée')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-date_emission', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_source', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('HOSPITALISATION', 'Hospitalisation'), ('INTERVENTION', 'Intervention chirurgicale'), ('DISPENSATION', 'Dispensation pharmacie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=16, verbose_name='origine')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="identifiant de l'acte")),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='montant')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture', verbose_name='facture')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'verbose_name_plural': 'lignes de facture',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('CARTE', 'Carte bancaire')], default='ESPECES', max_length=14, verbose_name='mode')),
                ('payeur', models.CharField(choices=[('PATIENT', 'Patient'), ('ASSURANCE', 'Assurance')], default='PATIENT', max_length=10, verbose_name='payeur')),
                ('est_remboursement', models.BooleanField(default=False, verbose_name='remboursement')),
                ('reference_transaction', models.CharField(blank=True, max_length=80, verbose_name='référence de transaction')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='commentaire')),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='facturation.facture', verbose_name='facture')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relance', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('canal', models.CharField(choices=[('TELEPHONE', 'Téléphone'), ('SMS', 'SMS'), ('COURRIER', 'Courrier'), ('EMAIL', 'Courriel'), ('GUICHET', 'Au guichet')], default='TELEPHONE', max_length=10, verbose_name='canal')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='commentaire')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='facturation.facture')),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relance',
                'verbose_name_plural': 'relances',
                'ordering': ['-date_relance'],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut', 'date_echeance'], name='facturation_statut_383511_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['patient', '-date_emission'], name='facturation_patient_67649f_idx'),
        ),
    ]
