# Generated by Django 5.2.17 on 2026-09-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='type_source',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('HOSPITALISATION', 'Hospitalisation'), ('INTERVENTION', 'Intervention chirurgicale'), ('DISPENSATION', 'Dispensation pharmacie'), ('EXAMEN', 'Analyse / imagerie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=16, verbose_name='origine'),
        ),
    ]
