# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0003_assurance_etablissement_and_more'),
        ('core', '0003_etablissement_historiqueaction_etablissement_and_more'),
        ('facturation', '0002_alter_lignefacture_type_source'),
        ('patients', '0002_allergie_etablissement_dossiermedical_etablissement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='relance',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reference',
            field=models.CharField(editable=False, max_length=20, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(editable=False, max_length=20, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='code',
            field=models.CharField(max_length=40, verbose_name='code'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.UniqueConstraint(fields=('etablissement', 'reference'), name='facture_reference_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(fields=('etablissement', 'reference'), name='paiement_reference_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='tarif',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='tarif_code_par_etablissement'),
        ),
    ]
