# Generated by Django 5.2.17 on 2026-09-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rattacher_donnees_existantes'),
        ('core', '0005_etablissement_obligatoire'),
        ('facturation', '0003_facture_etablissement_lignefacture_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
    ]
