# Generated by Django 5.2.17 on 2026-09-28 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0004_etablissement_obligatoire'),
        ('core', '0008_recaler_sequence_parametres'),
        ('patients', '0003_etablissement_obligatoire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierGrossesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(editable=False, max_length=20, verbose_name='référence')),
                ('date_dernieres_regles', models.DateField(verbose_name='date des dernières règles (1er jour)')),
                ('gestite', models.PositiveSmallIntegerField(default=1, help_text='Nombre total de grossesses, celle-ci comprise.', verbose_name='gestité')),
                ('parite', models.PositiveSmallIntegerField(default=0, help_text="Nombre d'accouchements antérieurs (au-delà de 22 semaines).", verbose_name='parité')),
                ('antecedents', models.TextField(blank=True, help_text='Césarienne, hémorragie, pré-éclampsie, diabète, drépanocytose, VIH…', verbose_name='antécédents obstétricaux et médicaux')),
                ('facteurs_risque', models.TextField(blank=True, verbose_name='facteurs de risque identifiés')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée (accouchement)'), ('INTERROMPUE', 'Interrompue (fausse couche, IVG médicale…)')], default='EN_COURS', max_length=12, verbose_name='statut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin de grossesse')),
                ('issue', models.TextField(blank=True, verbose_name='issue de la grossesse')),
                ('prochain_rdv', models.DateField(blank=True, editable=False, null=True, verbose_name='prochain rendez-vous')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('etablissement', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grossesses', to='patients.patient', verbose_name='patiente')),
                ('sage_femme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grossesses_suivies', to=settings.AUTH_USER_MODEL, verbose_name='suivi par')),
            ],
            options={
                'verbose_name': 'dossier de grossesse',
                'verbose_name_plural': 'dossiers de grossesse',
                'ordering': ['-date_dernieres_regles'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationPrenatale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(editable=False, verbose_name='n° de visite')),
                ('terme_sa', models.PositiveSmallIntegerField(editable=False, verbose_name='terme (SA)')),
                ('hauteur_uterine_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='hauteur utérine (cm)')),
                ('bruits_coeur_foetal', models.CharField(choices=[('NON_RECHERCHES', 'Non recherchés'), ('PRESENTS', 'Présents'), ('ABSENTS', 'Absents')], default='NON_RECHERCHES', max_length=16, verbose_name='bruits du cœur fœtal')),
                ('frequence_bcf', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='fréquence cardiaque fœtale (bpm)')),
                ('presentation', models.CharField(choices=[('NON_DETERMINEE', 'Non déterminée'), ('CEPHALIQUE', 'Céphalique'), ('SIEGE', 'Siège'), ('TRANSVERSE', 'Transverse')], default='NON_DETERMINEE', max_length=16, verbose_name='présentation')),
                ('oedemes', models.BooleanField(default=False, verbose_name='œdèmes (visage ou mains)')),
                ('albuminurie', models.CharField(choices=[('NON_FAIT', 'Non fait'), ('NEGATIF', 'Négatif'), ('TRACES', 'Traces'), ('PLUS1', '+'), ('PLUS2', '++'), ('PLUS3', '+++')], default='NON_FAIT', max_length=8, verbose_name='albuminurie')),
                ('glycosurie', models.CharField(choices=[('NON_FAIT', 'Non fait'), ('NEGATIF', 'Négatif'), ('TRACES', 'Traces'), ('PLUS1', '+'), ('PLUS2', '++'), ('PLUS3', '+++')], default='NON_FAIT', max_length=8, verbose_name='glycosurie')),
                ('hemoglobine_g_dl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='hémoglobine (g/dL)')),
                ('depistage_vih', models.CharField(choices=[('NON_FAIT', 'Non fait'), ('NEGATIF', 'Négatif'), ('POSITIF', 'Positif')], default='NON_FAIT', max_length=8, verbose_name='dépistage VIH')),
                ('depistage_syphilis', models.CharField(choices=[('NON_FAIT', 'Non fait'), ('NEGATIF', 'Négatif'), ('POSITIF', 'Positif')], default='NON_FAIT', max_length=8, verbose_name='dépistage syphilis')),
                ('tpi_sp_donne', models.BooleanField(default=False, verbose_name='SP donnée (prévention du paludisme)')),
                ('fer_acide_folique_donne', models.BooleanField(default=False, verbose_name='fer / acide folique donné')),
                ('vat_donne', models.BooleanField(default=False, verbose_name='vaccin antitétanique administré')),
                ('moustiquaire_remise', models.BooleanField(default=False, verbose_name='moustiquaire imprégnée remise')),
                ('observations', models.TextField(blank=True, verbose_name='observations et conseils donnés')),
                ('prochain_rdv', models.DateField(blank=True, null=True, verbose_name='prochain rendez-vous')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prenatale', to='consultations.consultation', verbose_name='consultation')),
                ('etablissement', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='maternite.dossiergrossesse', verbose_name='dossier de grossesse')),
            ],
            options={
                'verbose_name': 'consultation prénatale',
                'verbose_name_plural': 'consultations prénatales',
                'ordering': ['dossier', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='dossiergrossesse',
            constraint=models.UniqueConstraint(fields=('etablissement', 'reference'), name='grossesse_reference_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='dossiergrossesse',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'EN_COURS')), fields=('patient',), name='une_grossesse_en_cours_par_patiente'),
        ),
        migrations.AddConstraint(
            model_name='consultationprenatale',
            constraint=models.UniqueConstraint(fields=('dossier', 'numero'), name='visite_numero_par_dossier'),
        ),
    ]
