# Generated by Django 5.2.17 on 2026-09-09 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(default='Kènèya Sô', max_length=200, verbose_name="nom de l'établissement")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='etablissement/', verbose_name='logo')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='courriel')),
                ('fuseau_horaire', models.CharField(default='Africa/Bamako', max_length=64, verbose_name='fuseau horaire')),
                ('langues_actives', models.JSONField(default=list, help_text='Codes des langues proposées dans l\'interface, ex. ["fr", "bm"].', verbose_name='langues actives')),
            ],
            options={
                'verbose_name': 'paramètres système',
                'verbose_name_plural': 'paramètres système',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('CONSULTATION', 'Consultation'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('AUTRE', 'Autre')], max_length=20, verbose_name='action')),
                ('objet_type', models.CharField(blank=True, max_length=100, verbose_name="type d'objet")),
                ('objet_id', models.CharField(blank=True, max_length=64, verbose_name="identifiant de l'objet")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='données complémentaires')),
                ('horodatage', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='horodatage')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "entrée du journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['objet_type', 'objet_id'], name='core_histor_objet_t_7130ae_idx'), models.Index(fields=['utilisateur', '-horodatage'], name='core_histor_utilisa_49ba1c_idx')],
            },
        ),
    ]
