# Generated by Django 5.2.17 on 2026-09-10 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='titre')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='message')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='lien')),
                ('lu', models.BooleanField(default=False, verbose_name='lu')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='créée le')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['destinataire', 'lu', '-cree_le'], name='core_notifi_destina_c513d8_idx')],
            },
        ),
    ]
