# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='identifiant court')),
                ('statut', models.CharField(choices=[('ESSAI', "Période d'essai"), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu')], default='ESSAI', max_length=10, verbose_name='statut')),
                ('essai_jusqu_au', models.DateField(blank=True, null=True, verbose_name="fin de la période d'essai")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='historiqueaction',
            name='etablissement',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='parametressysteme',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddConstraint(
            model_name='parametressysteme',
            constraint=models.UniqueConstraint(fields=('etablissement',), name='parametres_un_par_etablissement'),
        ),
    ]
