# Generated by Django 5.2.17 on 2026-09-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_etablissement_obligatoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=80, verbose_name='nom')),
                ('prix_mensuel', models.DecimalField(blank=True, decimal_places=0, help_text='Vide = à définir.', max_digits=10, null=True, verbose_name='prix mensuel (FCFA)')),
                ('max_utilisateurs', models.PositiveIntegerField(blank=True, help_text='Vide = illimité.', null=True, verbose_name='utilisateurs maximum')),
                ('actif', models.BooleanField(default=True, verbose_name="proposé à l'inscription")),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
                'ordering': ['prix_mensuel', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Vide = aucune limite.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etablissements', to='core.plan', verbose_name='plan'),
        ),
    ]
