# Generated by Django 5.2.17 on 2026-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recaler_sequence_parametres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'spécialité',
                'verbose_name_plural': 'spécialités',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='specialites',
            field=models.ManyToManyField(blank=True, help_text='Les spécialités que cet hôpital propose à ses patients.', related_name='etablissements', to='core.specialite', verbose_name='spécialités proposées'),
        ),
    ]
