# Generated by Django 5.2.17 on 2026-09-10 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalisation', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, unique=True, verbose_name='désignation')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='référence')),
                ('quantite_disponible', models.PositiveIntegerField(default=0, verbose_name='quantité disponible')),
                ('quantite_totale', models.PositiveIntegerField(default=0, verbose_name='quantité totale')),
                ('statut_sterilisation', models.CharField(choices=[('STERILISE', 'Stérilisé'), ('EN_STERILISATION', 'En stérilisation'), ('NON_STERILISE', 'Non stérilisé'), ('PERIME', 'Péremption de stérilité dépassée')], default='NON_STERILISE', max_length=16, verbose_name='statut de stérilisation')),
                ('date_sterilisation', models.DateField(blank=True, null=True, verbose_name='date de stérilisation')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'matériel de bloc',
                'verbose_name_plural': 'matériels de bloc',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='SalleOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='nom')),
                ('code', models.CharField(blank=True, max_length=12, verbose_name='code')),
                ('equipement', models.TextField(blank=True, verbose_name='équipement disponible')),
                ('capacite', models.PositiveSmallIntegerField(default=1, verbose_name='capacité (interventions simultanées)')),
                ('duree_nettoyage_min', models.PositiveSmallIntegerField(default=30, help_text='Temps tampon inséré automatiquement entre deux interventions.', verbose_name='temps de nettoyage (minutes)')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=12, verbose_name='statut')),
                ('actif', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'salle opératoire',
                'verbose_name_plural': 'salles opératoires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('motif_operation', models.TextField(verbose_name="motif de l'intervention")),
                ('diagnostic_preop', models.TextField(blank=True, verbose_name='diagnostic préopératoire')),
                ('materiel_specifique', models.TextField(blank=True, verbose_name='matériel spécifique requis')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de la demande')),
                ('date_heure_debut_prevue', models.DateTimeField(blank=True, null=True, verbose_name='début prévu')),
                ('duree_estimee_min', models.PositiveSmallIntegerField(default=60, verbose_name='durée estimée (minutes)')),
                ('niveau_urgence', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('URGENTE', 'Urgente'), ('EXTREME_URGENCE', 'Extrême urgence')], default='PROGRAMMEE', max_length=16, verbose_name="niveau d'urgence")),
                ('statut', models.CharField(choices=[('DEMANDEE', 'Demandée'), ('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('REPORTEE', 'Reportée'), ('ANNULEE', 'Annulée')], default='DEMANDEE', max_length=12, verbose_name='statut')),
                ('faisabilite_anesthesique_validee', models.BooleanField(default=False, verbose_name='faisabilité anesthésique validée')),
                ('protocole_anesthesie', models.TextField(blank=True, verbose_name="protocole d'anesthésie")),
                ('heure_entree_salle', models.DateTimeField(blank=True, null=True, verbose_name='entrée en salle')),
                ('heure_debut_intervention', models.DateTimeField(blank=True, null=True, verbose_name='début (incision)')),
                ('heure_fin_intervention', models.DateTimeField(blank=True, null=True, verbose_name="fin d'intervention")),
                ('heure_sortie_salle', models.DateTimeField(blank=True, null=True, verbose_name='sortie de salle')),
                ('incidents_peroperatoires', models.TextField(blank=True, verbose_name='incidents / complications')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="motif d'annulation / de report")),
                ('annule_le', models.DateTimeField(blank=True, null=True, verbose_name='annulée / reportée le')),
                ('anesthesiste_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='anesthésiste')),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chirurgien_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions_operees', to=settings.AUTH_USER_MODEL, verbose_name='chirurgien principal')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='hospitalisation.hospitalisation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='patients.patient', verbose_name='patient')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='bloc_operatoire.salleoperatoire', verbose_name='salle')),
            ],
            options={
                'verbose_name': 'intervention',
                'verbose_name_plural': 'interventions',
                'ordering': ['-date_heure_debut_prevue', '-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='CompteRenduOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('technique_operatoire', models.TextField(verbose_name='technique opératoire')),
                ('constatations', models.TextField(blank=True, verbose_name='constatations peropératoires')),
                ('complications', models.TextField(blank=True, verbose_name='complications')),
                ('suites_a_prevoir', models.TextField(blank=True, verbose_name='suites à prévoir')),
                ('prescription_postoperatoire', models.TextField(blank=True, verbose_name='prescription postopératoire')),
                ('redige_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='rédigé le')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('redige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='rédigé par')),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_rendu', to='bloc_operatoire.intervention', verbose_name='intervention')),
            ],
            options={
                'verbose_name': 'compte-rendu opératoire',
                'verbose_name_plural': 'comptes-rendus opératoires',
            },
        ),
        migrations.CreateModel(
            name='MaterielRequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField(default=1, verbose_name='quantité')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requis_par', to='bloc_operatoire.materielbloc')),
            ],
            options={
                'verbose_name': 'matériel requis',
                'verbose_name_plural': 'matériels requis',
            },
        ),
        migrations.CreateModel(
            name='IndisponibiliteSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('MAINTENANCE', 'Maintenance planifiée'), ('PANNE', "Panne d'équipement"), ('TRAVAUX', 'Travaux'), ('AUTRE', 'Autre')], default='MAINTENANCE', max_length=12, verbose_name='motif')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='bloc_operatoire.salleoperatoire')),
            ],
            options={
                'verbose_name': 'indisponibilité de salle',
                'verbose_name_plural': 'indisponibilités de salle',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TypeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True, verbose_name="libellé de l'acte")),
                ('specialite', models.CharField(blank=True, max_length=100, verbose_name='spécialité')),
                ('duree_standard_min', models.PositiveSmallIntegerField(default=60, verbose_name='durée standard (minutes)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('materiels', models.ManyToManyField(blank=True, related_name='types_intervention', through='bloc_operatoire.MaterielRequis', to='bloc_operatoire.materielbloc')),
            ],
            options={
                'verbose_name': "type d'intervention",
                'verbose_name_plural': "types d'intervention",
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='materielrequis',
            name='type_intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_requis', to='bloc_operatoire.typeintervention'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='type_intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='bloc_operatoire.typeintervention', verbose_name="type d'acte"),
        ),
        migrations.CreateModel(
            name='EtapeChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.CharField(choices=[('AVANT_INDUCTION', "Avant l'induction anesthésique"), ('AVANT_INCISION', "Avant l'incision"), ('AVANT_SORTIE_SALLE', 'Avant la sortie de salle')], max_length=20, verbose_name='temps')),
                ('valide', models.BooleanField(default=False, verbose_name='validé')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='réserves / commentaire')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='bloc_operatoire.intervention')),
            ],
            options={
                'verbose_name': 'étape de checklist',
                'verbose_name_plural': 'checklist de sécurité',
                'ordering': ['intervention', 'temps'],
                'constraints': [models.UniqueConstraint(fields=('intervention', 'temps'), name='checklist_temps_unique')],
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHIRURGIEN', 'Chirurgien'), ('CHIRURGIEN_AIDE', 'Chirurgien aide'), ('ANESTHESISTE', 'Anesthésiste'), ('IBODE', 'IBODE'), ('AIDE_OPERATOIRE', 'Aide-opératoire'), ('AUTRE', 'Autre')], max_length=16, verbose_name='rôle')),
                ('notifie_le', models.DateTimeField(blank=True, null=True, verbose_name='notifié le')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='bloc_operatoire.intervention', verbose_name='intervention')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_bloc', to=settings.AUTH_USER_MODEL, verbose_name='membre')),
            ],
            options={
                'verbose_name': "membre d'équipe",
                'verbose_name_plural': 'équipe chirurgicale',
                'constraints': [models.UniqueConstraint(fields=('intervention', 'utilisateur'), name='membre_equipe_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='materielrequis',
            constraint=models.UniqueConstraint(fields=('type_intervention', 'materiel'), name='materiel_requis_unique'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['statut', 'date_heure_debut_prevue'], name='bloc_operat_statut_a4dcff_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['salle', 'date_heure_debut_prevue'], name='bloc_operat_salle_i_23dca6_idx'),
        ),
    ]
