# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc_operatoire', '0001_initial'),
        ('core', '0003_etablissement_historiqueaction_etablissement_and_more'),
        ('hospitalisation', '0002_chambre_etablissement_hospitalisation_etablissement_and_more'),
        ('patients', '0002_allergie_etablissement_dossiermedical_etablissement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compterenduoperatoire',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='etapechecklist',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='indisponibilitesalle',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='materielbloc',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='materielrequis',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='salleoperatoire',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='typeintervention',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='reference',
            field=models.CharField(editable=False, max_length=20, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='materielbloc',
            name='designation',
            field=models.CharField(max_length=150, verbose_name='désignation'),
        ),
        migrations.AlterField(
            model_name='salleoperatoire',
            name='nom',
            field=models.CharField(max_length=80, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='typeintervention',
            name='libelle',
            field=models.CharField(max_length=150, verbose_name="libellé de l'acte"),
        ),
        migrations.AddConstraint(
            model_name='intervention',
            constraint=models.UniqueConstraint(fields=('etablissement', 'reference'), name='intervention_reference_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='materielbloc',
            constraint=models.UniqueConstraint(fields=('etablissement', 'designation'), name='materielbloc_designation_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='salleoperatoire',
            constraint=models.UniqueConstraint(fields=('etablissement', 'nom'), name='salleoperatoire_nom_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='typeintervention',
            constraint=models.UniqueConstraint(fields=('etablissement', 'libelle'), name='typeintervention_libelle_par_etablissement'),
        ),
    ]
