# Generated by Django 5.2.17 on 2026-09-09 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_libelle', models.CharField(blank=True, help_text='Copie du libellé au moment de la prescription.', max_length=255, verbose_name='libellé prescrit')),
                ('posologie', models.CharField(help_text='Ex. : 1 comprimé matin et soir.', max_length=255, verbose_name='posologie')),
                ('duree_jours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='durée (jours)')),
                ('quantite_prescrite', models.PositiveIntegerField(blank=True, help_text="Nombre total d'unités à dispenser.", null=True, verbose_name='quantité à délivrer')),
                ('instructions', models.CharField(blank=True, max_length=255, verbose_name='instructions complémentaires')),
            ],
            options={
                'verbose_name': "ligne d'ordonnance",
                'verbose_name_plural': "lignes d'ordonnance",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('date_prescription', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de prescription')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('TRANSMISE', 'Transmise à la pharmacie'), ('DISP_PARTIELLE', 'Dispensée partiellement'), ('DISPENSEE', 'Dispensée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=16, verbose_name='statut')),
                ('date_transmission', models.DateTimeField(blank=True, null=True, verbose_name='date de transmission')),
                ('notes', models.TextField(blank=True, verbose_name='notes au pharmacien')),
            ],
            options={
                'verbose_name': 'ordonnance',
                'verbose_name_plural': 'ordonnances',
                'ordering': ['-date_prescription'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('date_consultation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de la consultation')),
                ('motif', models.CharField(max_length=255, verbose_name='motif de consultation')),
                ('histoire_maladie', models.TextField(blank=True, verbose_name='histoire de la maladie / symptômes')),
                ('examen_clinique', models.TextField(blank=True, verbose_name='examen clinique')),
                ('diagnostic', models.TextField(blank=True, verbose_name='diagnostic')),
                ('conduite_a_tenir', models.TextField(blank=True, verbose_name='conduite à tenir / traitement')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=10, verbose_name='statut')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient', verbose_name='patient')),
                ('praticien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='praticien')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Constantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='poids (kg)')),
                ('taille_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='taille (cm)')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='température (°C)')),
                ('tension_systolique', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TA systolique (mmHg)')),
                ('tension_diastolique', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TA diastolique (mmHg)')),
                ('frequence_cardiaque', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='fréquence cardiaque (bpm)')),
                ('frequence_respiratoire', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='fréquence respiratoire (cycles/min)')),
                ('saturation_o2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SpO₂ (%)')),
                ('glycemie_g_l', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='glycémie (g/L)')),
                ('releve_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='relevé le')),
                ('releve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='relevé par')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='consultations.consultation', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'constantes',
                'verbose_name_plural': 'constantes',
            },
        ),
    ]
