# Generated by Django 5.2.17 on 2026-09-09 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('pharmacie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneordonnance',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ordonnance', to='pharmacie.medicament', verbose_name='médicament'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='consultations.consultation', verbose_name='consultation'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='prescripteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to=settings.AUTH_USER_MODEL, verbose_name='prescripteur'),
        ),
        migrations.AddField(
            model_name='ligneordonnance',
            name='ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='consultations.ordonnance', verbose_name='ordonnance'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', '-date_consultation'], name='consultatio_patient_fb0946_idx'),
        ),
    ]
