# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        ('core', '0003_etablissement_historiqueaction_etablissement_and_more'),
        ('patients', '0002_allergie_etablissement_dossiermedical_etablissement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constantes',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='ligneordonnance',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='reference',
            field=models.CharField(editable=False, max_length=20, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='reference',
            field=models.CharField(editable=False, max_length=20, verbose_name='référence'),
        ),
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('etablissement', 'reference'), name='consultation_reference_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='ordonnance',
            constraint=models.UniqueConstraint(fields=('etablissement', 'reference'), name='ordonnance_reference_par_etablissement'),
        ),
    ]
