# Generated by Django 5.2.17 on 2026-09-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rattacher_donnees_existantes'),
        ('consultations', '0003_constantes_etablissement_consultation_etablissement_and_more'),
        ('core', '0005_etablissement_obligatoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantes',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='ligneordonnance',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='etablissement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
    ]
