# Generated by Django 5.2.17 on 2026-10-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_etablissement_obligatoire'),
        ('core', '0009_specialite_etablissement_specialites'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='core.specialite', verbose_name='spécialité'),
        ),
    ]
