# Generated by Django 5.2.17 on 2026-09-09 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('numero_dossier', models.CharField(editable=False, help_text='Identifiant unique du patient, attribué automatiquement.', max_length=20, unique=True, verbose_name='numéro de dossier')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('date_naissance_estimee', models.BooleanField(default=False, help_text="Cochez si seule l'année ou l'âge approximatif est connu.", verbose_name='date de naissance estimée')),
                ('lieu_naissance', models.CharField(blank=True, max_length=120, verbose_name='lieu de naissance')),
                ('nationalite', models.CharField(blank=True, default='Malienne', max_length=60, verbose_name='nationalité')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('ville', models.CharField(blank=True, max_length=120, verbose_name='ville / commune')),
                ('personne_a_prevenir', models.CharField(blank=True, max_length=150, verbose_name='personne à prévenir')),
                ('lien_personne_a_prevenir', models.CharField(blank=True, max_length=60, verbose_name='lien de parenté')),
                ('telephone_urgence', models.CharField(blank=True, max_length=40, verbose_name="téléphone d'urgence")),
                ('profession', models.CharField(blank=True, max_length=120, verbose_name='profession')),
                ('statut_matrimonial', models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve'), ('AUTRE', 'Autre')], max_length=20, verbose_name='statut matrimonial')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('INCONNU', 'Inconnu')], default='INCONNU', max_length=8, verbose_name='groupe sanguin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='photo')),
                ('actif', models.BooleanField(default=True, help_text='Décochez pour archiver le dossier sans le supprimer.', verbose_name='actif')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('antecedents_medicaux', models.TextField(blank=True, verbose_name='antécédents médicaux')),
                ('antecedents_chirurgicaux', models.TextField(blank=True, verbose_name='antécédents chirurgicaux')),
                ('antecedents_familiaux', models.TextField(blank=True, verbose_name='antécédents familiaux')),
                ('antecedents_gyneco_obstetricaux', models.TextField(blank=True, verbose_name='antécédents gynéco-obstétricaux')),
                ('traitements_en_cours', models.TextField(blank=True, verbose_name='traitements en cours')),
                ('habitudes_vie', models.TextField(blank=True, help_text='Tabac, alcool, activité physique, régime particulier…', verbose_name='habitudes de vie')),
                ('observations', models.TextField(blank=True, verbose_name='observations générales')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='patients.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'dossier médical',
                'verbose_name_plural': 'dossiers médicaux',
            },
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, verbose_name='allergène')),
                ('type', models.CharField(choices=[('MEDICAMENTEUSE', 'Médicamenteuse'), ('ALIMENTAIRE', 'Alimentaire'), ('ENVIRONNEMENTALE', 'Environnementale'), ('AUTRE', 'Autre')], default='MEDICAMENTEUSE', max_length=20, verbose_name='type')),
                ('severite', models.CharField(choices=[('LEGERE', 'Légère'), ('MODEREE', 'Modérée'), ('SEVERE', 'Sévère')], default='MODEREE', max_length=10, verbose_name='sévérité')),
                ('remarque', models.CharField(blank=True, max_length=255, verbose_name='remarque')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.dossiermedical', verbose_name='dossier médical')),
            ],
            options={
                'verbose_name': 'allergie',
                'verbose_name_plural': 'allergies',
                'ordering': ['libelle'],
                'constraints': [models.UniqueConstraint(fields=('dossier', 'libelle'), name='allergie_unique_par_dossier')],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nom', 'prenom'], name='patients_pa_nom_d8dfda_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['telephone'], name='patients_pa_telepho_3d0e80_idx'),
        ),
    ]
