# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_etablissement_historiqueaction_etablissement_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allergie',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='patient',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_dossier',
            field=models.CharField(editable=False, help_text='Identifiant unique du patient, attribué automatiquement.', max_length=20, verbose_name='numéro de dossier'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('etablissement', 'numero_dossier'), name='patient_numero_dossier_par_etablissement'),
        ),
    ]
