# Generated by Django 5.2.17 on 2026-10-08 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloc_operatoire', '0003_etablissement_obligatoire'),
        ('core', '0010_specialites_par_defaut'),
        ('hospitalisation', '0003_etablissement_obligatoire'),
        ('patients', '0003_etablissement_obligatoire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(editable=False, max_length=20, verbose_name='référence')),
                ('type_soin', models.CharField(choices=[('INJECTION', 'Injection'), ('PANSEMENT', 'Pansement'), ('PANSEMENT_POSTOP', 'Pansement post-opératoire'), ('PERFUSION', 'Perfusion'), ('SUTURE', 'Suture / retrait de fils'), ('AUTRE', 'Autre soin')], max_length=20, verbose_name='type de soin')),
                ('description', models.TextField(help_text="Produit, dose, voie d'administration, site, état de la plaie…", verbose_name='soin réalisé')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('date_soin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date du soin')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('etablissement', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='hospitalisation.hospitalisation', verbose_name='séjour')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='bloc_operatoire.intervention', verbose_name='intervention')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soins', to='patients.patient', verbose_name='patient')),
                ('soignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_realises', to=settings.AUTH_USER_MODEL, verbose_name='soignant')),
            ],
            options={
                'verbose_name': 'soin',
                'verbose_name_plural': 'soins',
                'ordering': ['-date_soin'],
                'indexes': [models.Index(fields=['patient', '-date_soin'], name='soins_soin_patient_ab0e79_idx')],
                'constraints': [models.UniqueConstraint(fields=('etablissement', 'reference'), name='soin_reference_par_etablissement')],
            },
        ),
    ]
