# Generated by Django 5.2.17 on 2026-09-10 16:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='nom')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('type', models.CharField(choices=[('PRIVEE', 'Compagnie privée'), ('MUTUELLE', 'Mutuelle'), ('ETAT', "Prise en charge de l'État"), ('ONG', 'ONG / organisme humanitaire'), ('AUTRE', 'Autre')], default='PRIVEE', max_length=10, verbose_name='type')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='interlocuteur')),
                ('contact_telephone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='courriel')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'assurance',
                'verbose_name_plural': 'assurances',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_adherent', models.CharField(blank=True, max_length=60, verbose_name="numéro d'adhérent")),
                ('taux_prise_en_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Surcharge le taux du contrat pour ce patient.', max_digits=5, null=True, verbose_name='taux spécifique (%)')),
                ('plafond_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='plafond spécifique (FCFA)')),
                ('date_debut', models.DateField(default=datetime.date.today, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'patient assuré',
                'verbose_name_plural': 'patients assurés',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='BordereauAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=24, unique=True, verbose_name='référence')),
                ('periode_debut', models.DateField(verbose_name='début de période')),
                ('periode_fin', models.DateField(verbose_name='fin de période')),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='généré le')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('SOLDE', 'Soldé')], default='BROUILLON', max_length=10, verbose_name='statut')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant total')),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bordereaux', to='assurances.assurance', verbose_name='assurance')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "bordereau d'assurance",
                'verbose_name_plural': "bordereaux d'assurance",
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='ContratAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé du contrat')),
                ('taux_prise_en_charge', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text="Part remboursée par l'assurance, de 0 à 100.", max_digits=5, verbose_name='taux de prise en charge (%)')),
                ('plafond_annuel', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour un contrat sans plafond.', max_digits=12, null=True, verbose_name='plafond annuel (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='assurances.assurance', verbose_name='assurance')),
            ],
            options={
                'verbose_name': "contrat d'assurance",
                'verbose_name_plural': "contrats d'assurance",
                'ordering': ['assurance__nom', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='LigneBordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_assurance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='part assurance')),
                ('bordereau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='assurances.bordereauassurance')),
            ],
            options={
                'verbose_name': 'ligne de bordereau',
                'verbose_name_plural': 'lignes de bordereau',
            },
        ),
    ]
