# Generated by Django 5.2.17 on 2026-09-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assurances', '0001_initial'),
        ('facturation', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebordereau',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bordereau', to='facturation.facture'),
        ),
        migrations.AddField(
            model_name='patientassure',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='assurances.contratassurance', verbose_name='contrat'),
        ),
        migrations.AddField(
            model_name='patientassure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='patients.patient', verbose_name='patient'),
        ),
        migrations.AddConstraint(
            model_name='contratassurance',
            constraint=models.UniqueConstraint(fields=('assurance', 'libelle'), name='contrat_unique_par_assurance'),
        ),
        migrations.AddConstraint(
            model_name='lignebordereau',
            constraint=models.UniqueConstraint(fields=('bordereau', 'facture'), name='ligne_bordereau_unique'),
        ),
    ]
