# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0002_initial'),
        ('core', '0003_etablissement_historiqueaction_etablissement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='bordereauassurance',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='contratassurance',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='patientassure',
            name='etablissement',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.etablissement', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='bordereauassurance',
            name='reference',
            field=models.CharField(editable=False, max_length=24, verbose_name='référence'),
        ),
        migrations.AddConstraint(
            model_name='assurance',
            constraint=models.UniqueConstraint(fields=('etablissement', 'nom'), name='assurance_nom_par_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='bordereauassurance',
            constraint=models.UniqueConstraint(fields=('etablissement', 'reference'), name='bordereauassurance_reference_par_etablissement'),
        ),
    ]
